spring:
  application:
    name: Forum
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bbs?serverTimezone=UTC
      username: root
      password: Abc12345.
  cache:
    redis:
      time-to-live: 1800000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8888


